FROM confluentinc/cp-kafka-connect:7.7.7

# Копируем локальную папку с плагином прямо в папку коннекторов Kafka Connect
COPY ./confluentinc-kafka-connect-elasticsearch-15.1.2 /usr/share/confluent-hub-components/confluentinc-kafka-connect-elasticsearch